### ISSUE TITLE
variadic method

### ISSUE THREAD

**Issue by marigs** [vektra/mockery#380]
Hello,

I have an interface with variadic method:
```
type Variadic interface {
	Multi(...int) int
}
```
and test for it:
```
func TestVariadic(t *testing.T) {
	variadic := mocks.Variadic{}

	variadic.On("Multi", []int{1, 2}).Return(43)
	variadic.Multi(1, 2)
}
```
it fails:
```
$ mockery --name Variadic
14 Apr 21 09:39 CEST INF Starting mockery dry-run=false version=v0.0.0-dev
14 Apr 21 09:39 CEST INF Walking dry-run=false version=v0.0.0-dev
14 Apr 21 09:39 CEST INF Generating mock dry-run=false interface=Variadic qualified-name=stringer version=v0.0.0-dev

$ go test -run TestVariadic ./...
--- FAIL: TestVariadic (0.00s)
panic: 

mock: Unexpected Method Call
-----------------------------

Multi(int,int)
		0: 1
		1: 2

The closest call I have is: 

Multi([]int)
		0: []int{1, 2}

Provided 1 arguments, mocked for 2 arguments
Diff: 0: FAIL:  (int=1) != ([]int=[1 2])
	1: FAIL:  (int=2) != (Missing) [recovered]
	panic: 

mock: Unexpected Method Call
-----------------------------

Multi(int,int)
		0: 1
		1: 2

The closest call I have is: 

Multi([]int)
		0: []int{1, 2}

Provided 1 arguments, mocked for 2 arguments
Diff: 0: FAIL:  (int=1) != ([]int=[1 2])
	1: FAIL:  (int=2) != (Missing)

goroutine 19 [running]:
testing.tRunner.func1.2(0x5c6600, 0xc000099180)
	/usr/local/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000082900)
	/usr/local/go/src/testing/testing.go:1147 +0x4b6
panic(0x5c6600, 0xc000099180)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/stretchr/testify/mock.(*Mock).fail(0xc0000aa460, 0x615242, 0x6f, 0xc0000f2a00, 0x4, 0x4)
	/home/marigs/play/go/mockery/stringer/vendor/github.com/stretchr/testify/mock/mock.go:254 +0x17f
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0000aa460, 0x66ebb6, 0x5, 0xc0000d2300, 0x2, 0x2, 0xc00009d410, 0x3, 0x3)
	/home/marigs/play/go/mockery/stringer/vendor/github.com/stretchr/testify/mock/mock.go:411 +0x65d
github.com/stretchr/testify/mock.(*Mock).Called(0xc0000aa460, 0xc0000d2300, 0x2, 0x2, 0x2, 0x2, 0x0)
	/home/marigs/play/go/mockery/stringer/vendor/github.com/stretchr/testify/mock/mock.go:383 +0x1ab
stringer/mocks.(*Variadic).Multi(0xc0000aa460, 0xc0000a4ac0, 0x2, 0x2, 0xc0000d92c0)
	/home/marigs/play/go/mockery/stringer/mocks/Variadic.go:20 +0x13b
stringer.TestVariadic(0xc000082900)
	/home/marigs/play/go/mockery/stringer/variadic_test.go:12 +0x195
testing.tRunner(0xc000082900, 0x61b0f8)
	/usr/local/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x2b3
FAIL	stringer	0.006s
?   	stringer/mocks	[no test files]
FAIL
```
Am I doing sth wrong here?

Looks similar to #215

**Comment by mneverov** [comment]
hi @marigs , could you please try `--unroll-variadic` flag?

**Comment by marigs** [comment]
Hi,

I have tried but did not help. Error is exactly the same

**Comment by LandonTClipp** [comment]
What does your mock look like? It's possible you need to specify `--unroll-variadic=False`

**Comment by marigs** [comment]
using `--unroll-variadic=False` it works. Thanks!
